galaxy_names = [
    [
        "Alpha",
        "Apus",
        "Aquila",
        "Ara",
        "Beta",
        "Canis",
        "Carina",
        "Comae",
        "Corona",
        "Crux",
        "Delta",
        "Draco",
        "Epsilon",
        "Gamma",
        "Lambda",
        "Lyra",
        "Nemo",
        "Omega",
        "Omicron",
        "Pavo",
        "Proxima",
        "Sagitta",
        "Serpens",
        "Sigma",
        "Theta",
        "Upsilon",
        "Ursa",
        "Vela",
        "Virgo",
        "Zeta",
    ],
    [
        "Acallaris",
        "Achelois",
        "Adastreia",
        "Aegialeus",
        "Aegimius",
        "Alatheia",
        "Alcyoneus",
        "Aldebaran",
        "Amphiaraus",
        "Anadeia",
        "Andromeda",
        "Aquarii",
        "Arcturus",
        "Aristaeus",
        "Asteria",
        "Asteropaios",
        "Astraeus",
        "Aurigae",
        "Boreas",
        "Borysthenis",
        "Calesius",
        "Capella",
        "Cassiopeia",
        "Centauri",
        "Centaurus",
        "Chronos",
        "Cymopoleia",
        "Dioscuri",
        "Draconis",
        "Eioneus",
        "Eridani",
        "Eridanus",
        "Eubuleus",
        "Euphorion",
        "Eusebeia",
        "Euthenia",
        "Hemithea",
        "Hyperbius",
        "Hyperes",
        "Hyperion",
        "Icarius",
        "Ichnaea",
        "Ilioneus",
        "Kentaurus",
        "Leporis",
        "Librae",
        "Lyrae",
        "Majoris",
        "Miriandynus",
        "Myrmidon",
        "Nebula",
        "Nemesis",
        "Odysseus",
        "Ophiuchi",
        "Orion",
        "Orionis",
        "Orithyia",
        "Palioxis",
        "Peleus",
        "Perileos",
        "Perseus",
        "Phoroneus",
        "Polystratus",
        "Porphyrion",
        "Proioxis",
        "Sagittarius",
        "Sirius",
        "Solymus",
        "Zagreus",
        "Zephyrus",
    ],
    [
        "Abyss",
        "Acorn",
        "Arrowhead",
        "Banana",
        "Beansprout",
        "Beanstalk",
        "Bell",
        "Blue Ribbon",
        "Blueberry",
        "Bottleneck",
        "Bowl",
        "Bull's Eye",
        "Bullet",
        "Butterfly",
        "Cat's Ear",
        "Cat's Eye",
        "Catterpillar",
        "Cherry",
        "Chickpea",
        "Clover",
        "Coconut",
        "Comet",
        "Crescent",
        "Crow's Feet",
        "Crown",
        "Dandelion",
        "Diamond",
        "Dragontooth",
        "Droplet",
        "Eagle Claw",
        "Eggshell",
        "Exploding",
        "Eyebrow",
        "Eyelash",
        "Falling",
        "Feather",
        "Fern Leaf",
        "Fingerprint",
        "Fisheye",
        "Fishscale",
        "Flame",
        "Football",
        "Grain",
        "Halo",
        "Heart",
        "Horseshoe",
        "Hurricane",
        "Icicle",
        "Iris",
        "Jellyfish",
        "Kettle",
        "Leaf",
        "Lemon",
        "Lightbulb",
        "Lilypad",
        "Lion's Mane",
        "Lion's Tail",
        "Maelstrom",
        "Meridian",
        "Mosaic",
        "Mouse",
        "Octopus",
        "Oculus",
        "Onion",
        "Owl Head",
        "Pear",
        "Pepper",
        "Pig's Tail",
        "Pinecone",
        "Ponytail",
        "Potato",
        "Red Ribbon",
        "Rippled",
        "Rose Petal",
        "Sawblade",
        "Seashell",
        "Serpent",
        "Serpent's Eye",
        "Sharkfin",
        "Sharktooth",
        "Shield",
        "Shooting Star",
        "Snail Shell",
        "Snowflake",
        "Soap Bubble",
        "Sparrow",
        "Spearpoint",
        "Spiderleg",
        "Spiderweb",
        "Spiral",
        "Starfish",
        "Strawberry",
        "Teacup",
        "Tiara",
        "Tiger Paw",
        "Tree Root",
        "Tree Trunk",
        "Turtle Shell",
        "Vortex",
        "Wave",
        "Whale's Tail",
        "Zodiac",
    ],
    [
        "Nebula",
        "Galaxy",
        "Cloud",
        "Star System",
    ],
]