ITEMS = [
    "An unfavorable wind blowing the ship towards shore. Sailing into the wind means tacking, which is hard and exhausting work for the crew and navigator.",
    "A Blue sea dragon demands tribute, Gold, Valuables, or Blood",
    "A Crate with a cures Crown made of blue scales and golden thorns",
    "A Floating bottle with a Treasure map inside! (DC 18 to spot)",
    "A Floating Treasure chest filled with GOLD! PAYDAY! (Dex DC 17 to catch) (STR DC 15 to lift it out)",
    "A large sea creature surfaces nearby",
    "A Legendary Party boat floats by, almost like a floating city and they try to get the party to join!",
    "A marshy isthmus blocks the way ahead, the crew may have to get out and pull the ship across",
    "A mass of bubbles and cavitation beneath the ship cause it sink suddenly, before the bubbles cease and the now swamped vessel and crew must struggle to the surface.",
    "A Merchant ship who is willing to trade goods!",
    "A pre-existing naval battle between two opposing fleets. Dare they try to navigate around them, or will they push forwards and into the crossfire?",
    "A tear in the Material Plane leading to the Elemental Plane of Water, causing more and more water to violently pour into the sea along with whatever creatures may follow… These could be the roughest waves seen to date!",
    "Ahead of the ship you can see a massive storm event. The distance to it and its size are indiscernible, but it looks like a hurricane, and the sudden choppy wake only confirms it.",
    "An Aquamarine Sea Dragon appears, and, with cooperation, blesses the crew",
    "An unexpected desert island (Very small) In the distance, with an NPC trying to flag the ship (DC 18 perception)",
    "Beautiful sunset, no clouds, decent winds but not very fast",
    "Castaways on a lifeboat needing help,",
    "Choppy grey waters that elude to a storm despite a mostly clear sky",
    "Choppy seas on a sunny day. Tritons and Kuo-ta wage battle just beneath the surface.",
    "Clear skies wind against",
    "Clear sunny skies no wind",
    "Cloudy and Rainy with capsizable waves",
    "Cloudy and Rainy with Favorable winds",
    "Cloudy and the wind is running away with the ship",
    "Cloudy with choppy seas, struggle to maintain direction",
    "Cold air, travel waters become half ocean half ice sludge; impedes travel to a slow pace",
    "Crimson floods the sky and the moon seems closer than usual. The water seems to be behaving… for now.",
    "Dark night, not a star in the sky – making night time navigation difficult",
    "Dark, cloudy sky and cold air. Dark shadows swim beneath what at first glance appears to be an empty ocean",
    "Doldrums – scorching heat, clear sky, no wind whatsoever. Better have packed fresh water.",
    "Foggy and no wind to guide direction",
    "Frenzy of flying fish feeding in fog upon which the frequency and size of the fish increases over time eventually overwhelming even the largest ships as the fattest whale sized flying fish slap down onto the decks",
    "glowing woman appears in front of the ship. (Ghost Encounter)",
    "Green waters that move unnaturally, it’s unclear if it really is water or not",
    "Heavy winds creating a waterspout",
    "In the middle of the deep the water becomes still; Lilly pads grow on the surface and the water is rich with vegetation and life.. the water is sweet and pleasant to drink",
    "Incredibly cold and slightly snowy, poor visibility",
    "It is overcast but otherwise calm, but the air is filled with static and occassionally lightning strikes in the distance.",
    "Jagged rocky spires suddenly jutting out of the ocean, corpses of boats litter them – requires expert and slow movement",
    "lear skies and favorable wind",
    "Lightning strikes the water up ahead.",
    "Mega waves sweeping across the deck of the boat",
    "Patches of the sea start bubbling, causing boats to sink",
    "Progressively larger icebergs float by, nearly hitting your ship, Mementos from each characters past bob up to the surface, yet when reached for, they reveal themselves as mirages. DC 12 DEX check to avoid falling in.",
    "Sargasaum. No wind or current, seaweed and garbage everywhere",
    "Scorching hot and stale winds",
    "Scratching sounds coming from outside the hull, heard belowdecks",
    "Shallow reefs or rocks make travel dangerous.",
    "Stormy the winds rip the sails",
    "Stormy, un-tamable winds",
    "Suddenly a meteor strikes the ocean not even 200 ft ahead of the ship. The massive energy from the impact suddenly creates a massive tidal wave like effect and heats the water so it burns to the touch.",
    "Sunny with light winds moving into sandbars",
    "Sunny, but with a light rain and a cold breeze",
    "The air is thick and humid, so much so that you can see the misty vapors as the light wind moves it.",
    "The boat sails past jetsam from a carnival boat",
    "The boat sails past thousands of dead fish",
    "The boatswain spies a spectral ship off the port bow!",
    "The party is visited by a god of chaos, and is willing to play a game, for a fee",
    "The sea and air taste sweet, not salty",
    "The sea is unusually calm, flat as far as the eye can see, makes a perfect reflection of the sky",
    "The seas are brimming with fish and life, dolphins accompany the boat as it glides though the water",
    "The water Begins to smell of rotten eggs (Con save)",
    "The water exudes a greenish mist, but is otherwise calm as one would expect from good weather at sea.",
    "The water is abnormally glassy, like an untouched lake.",
    "The water is abnormally salty and the ship seems unstably buoyant.",
    "The water seems normal. Fish are jumping out of the water in delight of the clear skies.",
    "The water seems to be accelerating towards port side. With careful inspection through a spyglass, you can see a large whirlpool in the distance.",
    "The water seems to be… boiling?",
    "The water suddenly goes silent and stops moving as the boat slides through the wake",
    "There are a suspicious amount of fish in these waters, almost as if they’re fleeing something",
    "There is a mirage of boats floating upside down beneath the water",
    "They are visited by a god one of the party members worship and is blessed.",
    "Unfavorable winds or currents requiring ‘kedging’ (using rowboats, ropes, pulleys, poles, and anchors to move the ship manually).",
    "You find a Derelict ship that’s better than theirs, with no crew on board.",
    "You hear arrhythmic soft thumps against the hull of the ship. Looking overboard is a sea of floating lifeless bodies.",
    "“What’s that singing I hear off in the distance?”",
    "A twenty-meter tall wave crashes into the hull of the ship, dealing 2d10 bludgeoning damage to the ship and players. (Players can make a DC 18 Dexterity saving throw to half the damage to themselves).",
    "The water in a 100-meter radius of the boat turns into magic ice which can be broken with either a DC 22 Strength check or the use of a damaging 1st-level spell or higher.",
    "Gale-force winds push you to your location at four times the traveling speed of your vessel for one hour. Each hour, any player on the top of the deck has to make a DC 10 Dexterity saving throw in order to no be thrown off the ship.",
    "An airship (see Unearthed Arcana: Of Ships and the Sea for star block) flies overhead and shoots a ballista (3d10 piercing damage) at your vessel.",
    "Strange magnetic ore in the coral reefs causes the compass to spin in circles.",
    "Several large ships seem to be chasing a smaller ship.",
    "Water in the area starts freezing, creating chunks of ice.",
    "You spot a ship circling a giant whirlpool. The ship cant quite seem to get enough speed to break free from the whirlpools grip.",
    "A forest of giant kelp starts brushing against the bottom of the ship.",
    "Discover a strong ocean current. Bonus points to speed if traveling in the same direction.",
    "Some titanic sized creature surfaces underneath the ship, lifting the ship out of the water. The creature is large enough to not have even noticed the ship or it’s crew.",
    "A sea monster leaps from the water and lands on the deck. It keeps pacing along the deck and stares over the rails while shivering.",
    "Hundreds of sea birds start landing on the deck.",
    "You spy a derelict ship. Upon closer inspection, it looks like the entire crew was massacred by something.",
    "You spy a large tower in the middle of the sea. As you get closer, you see several docks around it with several ships already docked. The tower is the entrance to an underwater city.",
    "You see a group of Sauhaugin riding towards you atop a pack of sharks. You’re under attack!",
    "You here a mysterious scratching from below deck. Further investigation reveals that it’s comg from underneath the ship.",
    "It is raining cats and dogs. All the meowing and barking is going to get annoying very quickly. The cats and dogs that land on deck seem ready to go to war.",
    "A water elemental emerges from the sea, attacking you and screaming about pollution.",
    "A group of sea elves swims up beside your ship, inviting you to visit an underwater city.",
    "A school of killer whales use their collective strength to push your ship off course. It seems like they want you to follow them.",
    "You are sailing into a lot of large rocks and many wrecked ships. This is a ship graveyard.",
    "A mesmerizing song on the wind beckons to you. Sailors must save or jump overboard and swim toward what each of them imagines is the source.",
    "Perfect weather. All clear.",
]
