items = [
    dict(roll=1, value="Пузырьки Вернона"),
    dict(roll=2, value="Центр Эликсиров Харро"),
    dict(roll=3, value="Шикарные Зелья"),
    dict(roll=4, value="Лечение Болячек"),
    dict(roll=5, value="Бурлящие Колбы"),
    dict(roll=6, value="Котел"),
    dict(roll=7, value="Таблетки Дарнелла"),
    dict(roll=8, value="Пузыри. Алхимия на Любой Случай"),
    dict(roll=9, value="У Дрипа и Дропа"),
    dict(roll=10, value="Верное Решение"),
    dict(roll=11, value="Алхимия Квикхенда"),
    dict(roll=12, value="Философский Камень"),
    dict(roll=13, value="Зелья от Патриции"),
    dict(roll=14, value="Кипящая Кастрюля"),
    dict(roll=15, value="Течение Жидкостей"),
    dict(roll=16, value="Алхимия Аллсиона"),
    dict(roll=17, value="Порошки и Зелья"),
    dict(roll=18, value="Налито и Закупорено"),
    dict(roll=19, value="Алхимия для Всех"),
    dict(roll=20, value="Эликсиры Эмеральдскейра"),
]
