items = [
    dict(roll=1, value="Мастерская Каменщика"),
    dict(roll=2, value="Наковальня"),
    dict(roll=3, value="Металлические Изделия Марвелла"),
    dict(roll=4, value="Стил и Сыновья"),
    dict(roll=5, value="Горн Ремесленника и Резчика"),
    dict(roll=6, value="Горн Точности"),
    dict(roll=7, value="Доспехи от Гуса"),
    dict(roll=8, value="Кузница Крепкого Молота"),
    dict(roll=9, value="Каление"),
    dict(roll=10, value="Изящество Аллхаммера"),
    dict(roll=11, value="Мастерская Брайтфайра"),
    dict(roll=12, value="Скрюченные Щипцы"),
    dict(roll=13, value="Литье Айронстронга"),
    dict(roll=14, value="Горн Тундерстрайка"),
    dict(roll=15, value="Стальные Изделия Стронгхенда"),
    dict(roll=16, value="Мехи Сильверчейна"),
    dict(roll=17, value="Медная Мастерская"),
    dict(roll=18, value="Мехи Беджерклоу"),
    dict(roll=19, value="Горн Изготовителя Мечей"),
    dict(roll=20, value="Творец Мифрила"),
]
