items = [
    dict(roll=1, value="У Пера"),
    dict(roll=2, value="Сказка Дракона"),
    dict(roll=3, value="Тома Талриеля"),
    dict(roll=4, value="Работы Врита"),
    dict(roll=5, value="Букинист Барнабус"),
    dict(roll=6, value="Компания Страницы"),
    dict(roll=7, value="В Истории"),
    dict(roll=8, value="Книжный Магазин Лезербаунда"),
    dict(roll=9, value="Продажа Книг Разлитые Чернила"),
    dict(roll=10, value="Любовное Письмо"),
    dict(roll=11, value="Закладка"),
    dict(roll=12, value="Подержаные Истории Алистии"),
    dict(roll=13, value="Уголок Книжного Червя"),
    dict(roll=14, value="Как Написано"),
    dict(roll=15, value="Книжный Магазин Предание и Далее"),
    dict(roll=16, value="Самые Высокие Истории"),
    dict(roll=17, value="Хроники у Картера"),
    dict(roll=18, value="Книжный Магазин Писатели Неправы"),
    dict(roll=19, value="Лавка Историй"),
    dict(roll=20, value="Страницы Рыцаря"),
]
